
import green from "../Activityimg/green.png";
import red from "../Activityimg/red.png";
import yellow from "../Activityimg/yellow.png";
import call from "../Activityimg/call.png";
import mail from "../Activityimg/yellow.png";
import whatsapp from "../Activityimg/whatsapp.png";

const Data = [
    {
        
        Status:green,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:call,mail,
    },
    {
        Status:green,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:red,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:green,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:yellow,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:green,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:red,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:yellow,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:red,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:green,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:yellow,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:red,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:green,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },
    {
        Status:red,
        CandidateName:'Akash Singh',
        Assingment:'Yes',
        ScreeningQuestions:'Yes',
        VirtualInvitation:'Yes',
        TelephonicInterview:'Yes',
        Shortlisted:'Yes',
        Contact:'',
    },

]
export default Data;