const BidData=[
    {
        posting:'UI / UX Designer',
        Timtobid:'5 min 20 sec',
        Bidrank:'#50 of 51 bids',
        Winningbid:'$400 USD',
        Yourbid:'$300 USD',
        Actiontaken:''
    },
    {
        posting:'UI / UX Designer',
        Timtobid:'5 min 20 sec',
        Bidrank:'#50 of 51 bids',
        Winningbid:'$400 USD',
        Yourbid:'$300 USD',
        Actiontaken:'',
    },
    {
        posting:'UI / UX Designer',
        Timtobid:'5 min 20 sec',
        Bidrank:'#50 of 51 bids',
        Winningbid:'$400 USD',
        Yourbid:'$300 USD',
        Actiontaken:'',
    },
    {
        posting:'UI / UX Designer',
        Timtobid:'5 min 20 sec',
        Bidrank:'#50 of 51 bids',
        Winningbid:'$400 USD',
        Yourbid:'$300 USD',
        Actiontaken:'',
    },
    {
        posting:'UI / UX Designer',
        Timtobid:'5 min 20 sec',
        Bidrank:'#50 of 51 bids',
        Winningbid:'$400 USD',
        Yourbid:'$300 USD',
        Actiontaken:'',
    },
    {
        posting:'UI / UX Designer',
        Timtobid:'5 min 20 sec',
        Bidrank:'#50 of 51 bids',
        Winningbid:'$400 USD',
        Yourbid:'$300 USD',
        Actiontaken:'',
    },
    {
        posting:'UI / UX Designer',
        Timtobid:'5 min 20 sec',
        Bidrank:'#50 of 51 bids',
        Winningbid:'$400 USD',
        Yourbid:'$300 USD',
        Actiontaken:'',
    },
    {
        posting:'UI / UX Designer',
        Timtobid:'5 min 20 sec',
        Bidrank:'#50 of 51 bids',
        Winningbid:'$400 USD',
        Yourbid:'$300 USD',
        Actiontaken:'',
    },
    {
        posting:'UI / UX Designer',
        Timtobid:'5 min 20 sec',
        Bidrank:'#50 of 51 bids',
        Winningbid:'$400 USD',
        Yourbid:'$300 USD',
        Actiontaken:'',
    },
]
export default BidData;